---
functional:
  - Возможность искать товары по ключевому слову
  - Возможность фильтровать товары по цене, бренду, категории, наличию
  - Возможность просматривать товары и подробную информацию о нем (название, рейтинг, цена со скидкой и без).
  - Возможность добавлять товары в корзину, просматривать содержимое корзины, удаления товара из корзины
  - Возможность оформление заказа с переходом на страницу оплаты
non-functional:
  - Веб-сайт должен быть оптимизирован для скорости работы.
  - Проверка UX/UI написания элементов на грамматические ошибки, удобный вывод на странице
  - Сайт должен быть безопасным и защищать данные пользователя
  - У сайта адаптивная верстка, чтобы он был удобным на мобильных устройствах.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Возможность переключения языка меню (английский-русский)
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Корзина с товарами сохраняется даже после того, как пользователь покинул страницу (страницу магазина – вышел из приложения)
implicit:
  - Локализация работы интернет-магазин. Несоответствие, для РФ – единицы, в которых указана стоимость.
  - Сообщение пользователю об успешной оплате товара (т.к. это основная задача интернет-магазина)


  
