---
functional:
  - Возможность искать товары по ключевому слову, категории
  - Возможность фильтровать товары по цене, бренду, категории
  - Возможность просматривать товары и просматривать подробную информацию о товаре
  - Возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Возможность переключения языка меню (английский-русский)
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Корзина с товарами сохраняется даже после того, как пользователь покинул страницу (страницу магазина – вышел из приложения)
implicit:
  - При сортировке по цене не может быть отрицательных чисел
  - Фильтровать по парно категорию, цену, наличие 
  - Фильтровать только по одной из позиций цене или наличию или категории
  - Возможность оформление заказа
  - Возможность удаления товара из корзины
  
